# This script was originally inside the faiss-sys/faiss directory
set -ex
# CMAKE_PREFIX_PATH="/opt/homebrew/opt/openblas" LC_ALL="C" "cmake" "-Wdev" "--debug-output" "/Users/siusherman/code/faiss-rs/faiss-sys/faiss" "-DFAISS_ENABLE_C_API=ON" "-DBUILD_SHARED_LIBS=OFF" "-DCMAKE_BUILD_TYPE=Release" "-DFAISS_ENABLE_GPU=OFF" "-DFAISS_ENABLE_PYTHON=OFF" "-DBUILD_TESTING=OFF" "-DCMAKE_SYSTEM_NAME=unknown" "-DCMAKE_SYSTEM_PROCESSOR=wasm32" "-DCMAKE_C_FLAGS= -ffunction-sections -fdata-sections -nostdlib -fno-exceptions --target=wasm32-unknown-unknown" "-DCMAKE_C_COMPILER=/opt/homebrew/opt/llvm/bin/clang" "-DCMAKE_CXX_FLAGS= -ffunction-sections -fdata-sections -fno-exceptions -nostdlib --target=wasm32-unknown-unknown -I/opt/homebrew/opt/libomp/include -I/opt/homebrew/opt/openblas/include" "-DCMAKE_CXX_COMPILER=/opt/homebrew/opt/llvm/bin/clang++" "-DCMAKE_ASM_FLAGS= -ffunction-sections -fdata-sections -fno-exceptions --target=wasm32-unknown-unknown" "-DCMAKE_ASM_COMPILER=/opt/homebrew/opt/llvm/bin/clang" "-DCMAKE_VERBOSE_MAKEFILE:BOOL=ON" -DCMAKE_TOOLCHAIN_FILE=../toolchain-wasm32.cmake/
export LDFLAGS="-L/opt/homebrew/opt/libomp/lib -L/opt/homebrew/opt/openblas/lib"
export CXXFLAGS="-I/opt/homebrew/opt/libomp/include -I/opt/homebrew/opt/openblas/include"
export LD_LIBRARY_PATH="/opt/homebrew/opt/libomp/lib:/opt/homebrew/opt/openblas/lib:/Users/shermansiu/code/faiss-rs/faiss-sys/faiss/c_api/"
rm faiss/CMakeCache.txt
CMAKE_PREFIX_PATH="/opt/homebrew/opt/openblas" LC_ALL="C" "cmake" "-Wdev" "--debug-output" "/Users/siusherman/code/faiss-rs/faiss-sys/faiss" "-DFAISS_ENABLE_C_API=ON" "-DBUILD_SHARED_LIBS=ON" "-DCMAKE_BUILD_TYPE=Release" "-DFAISS_ENABLE_GPU=OFF" "-DFAISS_ENABLE_PYTHON=OFF" "-DBUILD_TESTING=OFF" "-DCMAKE_C_FLAGS= -ffunction-sections -fdata-sections" "-DCMAKE_C_COMPILER=/opt/homebrew/opt/llvm/bin/clang" "-DCMAKE_CXX_FLAGS= -ffunction-sections -fdata-sections -I/opt/homebrew/opt/libomp/include -I/opt/homebrew/opt/openblas/include -L/opt/homebrew/opt/libomp/lib -L/opt/homebrew/opt/openblas/lib -lomp -lblas -llapack" "-DCMAKE_CXX_COMPILER=/opt/homebrew/opt/llvm/bin/clang++" "-DCMAKE_ASM_FLAGS= -ffunction-sections -fdata-sections" "-DCMAKE_ASM_COMPILER=/opt/homebrew/opt/llvm/bin/clang" "-DCMAKE_VERBOSE_MAKEFILE:BOOL=ON" -DLIBCXX_ENABLE_VENDOR_AVAILABILITY_ANNOTATIONS=ON -DCMAKE_OSX_SYSROOT=/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk -DDEFAULT_SYSROOT=/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk -DCMAKE_BUILD_TYPE=Release
cmake --build faiss/c_api
